#!/bin/sh

# https://git-scm.com/docs/githooks#_post_merge
# This hook is invoked by (git-merge[1])[https://git-scm.com/docs/git-merge],
# which happens when a `git pull` is done on a local repository (or `git fetch; git merge`).
# Any scripts included below will be run at that time

#---------------------------------------------
# This script detects changes on Gemfile and migrations folder and notifies user
# This is automatically placed in .git/hooks/post-merge after bootstrapping project
# Credit: https://medium.com/@edgar/using-a-git-hook-to-know-when-to-run-rails-migrations-and-install-new-gems-146afa254a92
#---------------------------------------------
diff=$(git diff --name-only HEAD@{1} HEAD)

migrate=$(expr "$diff" : ".*db/migrate.*")
bundle=$(expr "$diff" : ".*Gemfile*")

if [ ! "$bundle" -eq 0 ]
then
    title='Bundle needed!'
    message="You should run 'bundle install'"
    appname="Git merge"
    command -v notify-send >/dev/null 2>&1 && notify-send --icon=info "$title" "$message"
    command -v growlnotify >/dev/null 2>&1 && growlnotify -n "$appname" -m "$message" -t "$title"
    echo ""
    echo "###################################"
    echo "#  Changes in Gemfile detected!   #"
    echo "# You should run 'bundle install' #"
    echo "###################################"
    echo ""
fi

if [ ! "$migrate" -eq 0 ]
then
    title='Migration needed!'
    message="You should run 'rake db:migrate'"
    appname="Git merge"
    command -v notify-send >/dev/null 2>&1 && notify-send --icon=info "$title" "$message"
    command -v growlnotify >/dev/null 2>&1 && growlnotify -n "$appname" -m "$message" -t "$title"
    echo ""
    echo "####################################"
    echo "#     Migration file detected!     #"
    echo "# You should run 'rake db:migrate' #"
    echo "####################################"
    echo ""
fi
