#!/bin/sh

# https://git-scm.com/docs/githooks#_pre_push
# This hook is invoked by (git-push[1])[https://git-scm.com/docs/git-push]
# and can be used to prevent a push from taking place.
# It's typically used to verify committed code before pushing it to a remote

#---------------------------------------------
# Run static analysis & tests before pushing
#---------------------------------------------

bin/start
bin/rake code:analysis
bin/rspec .

# === OR ===
# tho it seems to need a db connection to run tests

# bundle exec rake code:analysis
# bundle exec rspec
